name: repos
description: GitHub repos viewer with React in Dart
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_react:
    git:
      url: https://github.com/MelbourneDeveloper/dart_node.git
      path: packages/dart_node_react
  nadz: ^0.0.7-beta

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
